spring.application.name=data-binding-validate


spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123456$
spring.datasource.driver-class-name=org.postgresql.Driver

# C?u hình JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# cloudinary
cloud-name=dwqmfiprt
api-key=547165255154353
api-secret=vzEY6Tk0t_mKQw3V5yfDB0F1LPI
